version: '3'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: magnum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data



  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Use your Django Dockerfile
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    # networks:
    #   - WIP_network
    # depends_on:
    restart: always  # Add this line for automatic restart
    #   - database  # If you have a separate database container