# Generated by Django 4.2.6 on 2024-01-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0053_excelimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemachineconfig',
            name='break_time',
            field=models.CharField(blank=True, default='01:00:00', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machinewisedata',
            name='assembly_line',
            field=models.CharField(default='AssemblyLine - 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='machinewisedata',
            name='plant',
            field=models.CharField(default='Chennai', max_length=255),
        ),
        migrations.AlterField(
            model_name='machinewisedata',
            name='shopfloor',
            field=models.CharField(default='Shopfloor - 1', max_length=255),
        ),
    ]
