# Generated by Django 4.2.6 on 2024-02-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0054_alter_linemachineconfig_break_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinewisedata',
            name='product_target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
