# Generated by Django 4.2.6 on 2024-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0056_alter_machinewisedata_product_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinewisedata',
            name='gap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
