# Generated by Django 4.2.6 on 2024-02-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0058_testtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinewisedata',
            name='idle_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinewisedata',
            name='on_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
