# Generated by Django 4.2.6 on 2024-02-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0059_alter_machinewisedata_idle_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soloassemblylinedata',
            name='mc_idle_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soloassemblylinedata',
            name='mc_on_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
